@startuml
用户 -> 抖音APP界面:  1、打开抖音APP
抖音APP界面 --> 用户: 2、显示抖音APP界面
用户 -> 抖音APP界面:  3.1、为某一视频点赞
用户 -> 智能推荐系统:  3.1、为某一视频点赞
抖音APP界面--> 用户: 3.2、该视频点赞数加一
智能推荐系统 -> 智能推荐系统:3.3、后台智能推荐系统搜集用户兴趣
智能推荐系统 -> 抖音APP界面:3.4、推送与被点赞视频相关的视频
抖音APP界面 -> 用户:3.5、显示在抖音APP界面

@enduml