@startuml
用户 -> 抖音APP界面:  1、打开抖音APP
抖音APP界面 --> 用户: 2、显示抖音APP界面
用户 -> 抖音APP界面:  3、点击界面上“新建视频”
抖音APP界面--> 用户: 4、显示拍摄视频页
用户 -> 抖音APP界面:5.1、拍摄视频并上传
用户 -> 智能推荐系统:5.1、拍摄视频并上传
智能推荐系统 -> 智能推荐系统:5.2、后台智能推荐系统将该视频分发给其他用户
智能推荐系统 -> 智能推荐系统:5.3、根据拍摄的视频为该用户推送相关视频
智能推荐系统 -> 抖音APP界面:5.4、显示相关视频在抖音APP界面
抖音APP界面 -> 用户:5.5、用户观看视频

@enduml